// <auto-generated />
using System;
using Kalm.Api.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Kalm.Api.Migrations
{
    [DbContext(typeof(KalmDbContext))]
    [Migration("20260715140000_InitialFoundation")]
    partial class InitialFoundation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasDefaultSchema("platform");

            modelBuilder.Entity("Kalm.Api.Persistence.IdempotencyRecord", b =>
            {
                b.Property<Guid>("Id")
                    .HasColumnType("uuid")
                    .HasColumnName("id");

                b.Property<DateTimeOffset>("CreatedAtUtc")
                    .HasColumnType("timestamptz")
                    .HasColumnName("created_at_utc");

                b.Property<string>("Key")
                    .IsRequired()
                    .HasMaxLength(128)
                    .HasColumnType("character varying(128)")
                    .HasColumnName("key");

                b.Property<string>("RequestHash")
                    .IsRequired()
                    .HasMaxLength(128)
                    .HasColumnType("character varying(128)")
                    .HasColumnName("request_hash");

                b.Property<string>("ResponseBody")
                    .IsRequired()
                    .HasColumnType("jsonb")
                    .HasColumnName("response_body");

                b.HasKey("Id").HasName("pk_idempotency_records");
                b.HasIndex("Key")
                    .IsUnique()
                    .HasDatabaseName("ix_idempotency_records_key");
                b.ToTable("idempotency_records", "platform");
            });

            modelBuilder.Entity("Kalm.Api.Persistence.OutboxMessage", b =>
            {
                b.Property<Guid>("Id")
                    .HasColumnType("uuid")
                    .HasColumnName("id");

                b.Property<string>("Error")
                    .HasMaxLength(2048)
                    .HasColumnType("character varying(2048)")
                    .HasColumnName("error");

                b.Property<DateTimeOffset>("OccurredAtUtc")
                    .HasColumnType("timestamptz")
                    .HasColumnName("occurred_at_utc");

                b.Property<string>("Payload")
                    .IsRequired()
                    .HasColumnType("jsonb")
                    .HasColumnName("payload");

                b.Property<DateTimeOffset?>("ProcessedAtUtc")
                    .HasColumnType("timestamptz")
                    .HasColumnName("processed_at_utc");

                b.Property<string>("Type")
                    .IsRequired()
                    .HasMaxLength(256)
                    .HasColumnType("character varying(256)")
                    .HasColumnName("type");

                b.HasKey("Id").HasName("pk_outbox_messages");
                b.HasIndex("ProcessedAtUtc", "OccurredAtUtc")
                    .HasDatabaseName("ix_outbox_messages_processed_at_utc_occurred_at_utc");
                b.ToTable("outbox_messages", "platform");
            });

            modelBuilder.Entity("Kalm.Api.Persistence.SchemaMarker", b =>
            {
                b.Property<Guid>("Id")
                    .HasColumnType("uuid")
                    .HasColumnName("id");

                b.Property<DateTimeOffset>("CreatedAtUtc")
                    .HasColumnType("timestamptz")
                    .HasColumnName("created_at_utc");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasMaxLength(128)
                    .HasColumnType("character varying(128)")
                    .HasColumnName("name");

                b.HasKey("Id").HasName("pk_schema_markers");
                b.HasIndex("Name")
                    .IsUnique()
                    .HasDatabaseName("ix_schema_markers_name");
                b.ToTable("schema_markers", "platform");
            });
#pragma warning restore 612, 618
        }
    }
}
