import type { Language } from "../../core/i18n/language.service";

export const ROLE_GROUP_LABELS: Record<Language, Record<string, string>> = {
  en: {
    management: "Management",
    usersRoles: "Users and roles",
    branchesDevices: "Branches and devices",
    catalogPricing: "Catalog and pricing",
    posOrders: "POS and orders",
    kds: "KDS",
    shiftsCash: "Shifts and cash",
    inventory: "Inventory",
    purchasingSuppliers: "Purchasing and suppliers",
    expenses: "Expenses",
    reports: "Reports",
    auditSettingsBackups: "Audit, settings, and backups"
  },
  ar: {
    management: "الإدارة",
    usersRoles: "المستخدمون والأدوار",
    branchesDevices: "الفروع والأجهزة",
    catalogPricing: "الكتالوج والتسعير",
    posOrders: "نقطة البيع والطلبات",
    kds: "شاشة التحضير",
    shiftsCash: "الورديات والنقدية",
    inventory: "المخزون",
    purchasingSuppliers: "المشتريات والموردون",
    expenses: "المصروفات",
    reports: "التقارير",
    auditSettingsBackups: "التدقيق والإعدادات والنسخ الاحتياطي"
  }
};

export const ROLES_COPY = {
  en: {
    nav: "Roles",
    heading: "Roles",
    supporting: "Create clear permission sets for the people who operate Kalm.",
    create: "Create role",
    search: "Search roles",
    searchPlaceholder: "Role name",
    status: "Status",
    active: "Active",
    archived: "Archived",
    all: "All",
    name: "Role name",
    permissions: "Permissions",
    assignments: "Assignments",
    actions: "Actions",
    edit: "Edit",
    previous: "Previous",
    next: "Next",
    empty: "No roles match this view.",
    loadError: "Roles could not be loaded.",
    retry: "Try again",
    loading: "Loading roles…",
    newHeading: "Create role",
    editHeading: "Edit role",
    roleName: "Role name",
    roleNameRequired: "Enter a role name.",
    permissionSearch: "Search permissions",
    permissionSearchPlaceholder: "Label, description, or code",
    selected: "selected",
    permissionRequired: "Select at least one permission.",
    save: "Save role",
    saving: "Saving…",
    cancel: "Back to roles",
    protectedHeading: "Protected system role",
    protectedMessage: "This role is maintained only through the trusted operational recovery command.",
    archivedMessage: "This archived role is read-only.",
    conflictHeading: "A newer version is available",
    conflictMessage: "Your draft is preserved. Reload the latest role before deciding how to continue.",
    reloadLatest: "Reload latest",
    archive: "Archive role",
    archiveHeading: "Archive this role?",
    archiveMessage: "Archived roles remain in history and cannot be restored in this release.",
    confirmArchive: "Archive",
    dismiss: "Cancel",
    assignedArchive: "This role cannot be archived while it has active assignments.",
    saveError: "The role could not be saved.",
    archiveError: "The role could not be archived.",
    saved: "Role saved.",
    archivedNotice: "Role archived.",
    permissionCode: "Permission code"
  },
  ar: {
    nav: "الأدوار",
    heading: "الأدوار",
    supporting: "أنشئ مجموعات صلاحيات واضحة للأشخاص الذين يديرون عمليات كالم.",
    create: "إنشاء دور",
    search: "البحث في الأدوار",
    searchPlaceholder: "اسم الدور",
    status: "الحالة",
    active: "نشط",
    archived: "مؤرشف",
    all: "الكل",
    name: "اسم الدور",
    permissions: "الصلاحيات",
    assignments: "التعيينات",
    actions: "الإجراءات",
    edit: "تعديل",
    previous: "السابق",
    next: "التالي",
    empty: "لا توجد أدوار مطابقة لهذا العرض.",
    loadError: "تعذر تحميل الأدوار.",
    retry: "إعادة المحاولة",
    loading: "جارٍ تحميل الأدوار…",
    newHeading: "إنشاء دور",
    editHeading: "تعديل الدور",
    roleName: "اسم الدور",
    roleNameRequired: "أدخل اسمًا للدور.",
    permissionSearch: "البحث في الصلاحيات",
    permissionSearchPlaceholder: "التسمية أو الوصف أو الرمز",
    selected: "محدد",
    permissionRequired: "حدد صلاحية واحدة على الأقل.",
    save: "حفظ الدور",
    saving: "جارٍ الحفظ…",
    cancel: "العودة إلى الأدوار",
    protectedHeading: "دور نظام محمي",
    protectedMessage: "تتم صيانة هذا الدور فقط من خلال أمر الاستعادة التشغيلي الموثوق.",
    archivedMessage: "هذا الدور المؤرشف للقراءة فقط.",
    conflictHeading: "يتوفر إصدار أحدث",
    conflictMessage: "تم الاحتفاظ بمسودتك. حمّل أحدث إصدار قبل تحديد كيفية المتابعة.",
    reloadLatest: "تحميل الأحدث",
    archive: "أرشفة الدور",
    archiveHeading: "هل تريد أرشفة هذا الدور؟",
    archiveMessage: "تبقى الأدوار المؤرشفة في السجل ولا يمكن استعادتها في هذا الإصدار.",
    confirmArchive: "أرشفة",
    dismiss: "إلغاء",
    assignedArchive: "لا يمكن أرشفة هذا الدور بينما توجد له تعيينات نشطة.",
    saveError: "تعذر حفظ الدور.",
    archiveError: "تعذر أرشفة الدور.",
    saved: "تم حفظ الدور.",
    archivedNotice: "تمت أرشفة الدور.",
    permissionCode: "رمز الصلاحية"
  }
} as const;
