// <auto-generated />
using System;
using Kalm.Identity.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Kalm.Identity.Infrastructure.Migrations
{
    [DbContext(typeof(IdentityDbContext))]
    partial class IdentityDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("identity")
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Kalm.Identity.Domain.LoginAttempt", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("correlation_id");

                    b.Property<int>("FingerprintKeyVersion")
                        .HasColumnType("integer")
                        .HasColumnName("fingerprint_key_version");

                    b.Property<string>("IdentifierFingerprint")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("identifier_fingerprint");

                    b.Property<string>("NetworkIdentifier")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("network_identifier");

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .HasColumnType("timestamptz")
                        .HasColumnName("occurred_at_utc");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("outcome");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("IdentifierFingerprint", "OccurredAtUtc")
                        .HasDatabaseName("ix_login_attempts_identifier_fingerprint_occurred_at_utc");

                    b.HasIndex("NetworkIdentifier", "OccurredAtUtc")
                        .HasDatabaseName("ix_login_attempts_network_identifier_occurred_at_utc");

                    b.HasIndex("UserId", "OccurredAtUtc")
                        .HasDatabaseName("ix_login_attempts_user_id_occurred_at_utc");

                    b.ToTable("login_attempts", "identity", t =>
                        {
                            t.HasCheckConstraint("ck_login_attempts_outcome", "outcome in ('Succeeded', 'InvalidCredentials', 'Locked', 'Ineligible')");
                        });
                });

            modelBuilder.Entity("Kalm.Identity.Domain.PasswordCredential", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("EncodedHash")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("encoded_hash");

                    b.Property<int>("FailedAttemptCount")
                        .HasColumnType("integer")
                        .HasColumnName("failed_attempt_count");

                    b.Property<DateTimeOffset?>("FailureWindowStartedAtUtc")
                        .HasColumnType("timestamptz")
                        .HasColumnName("failure_window_started_at_utc");

                    b.Property<DateTimeOffset?>("LockedUntilUtc")
                        .HasColumnType("timestamptz")
                        .HasColumnName("locked_until_utc");

                    b.Property<DateTimeOffset?>("PasswordChangedAtUtc")
                        .HasColumnType("timestamptz")
                        .HasColumnName("password_changed_at_utc");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at_utc");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("ux_password_credentials_user_id");

                    b.ToTable("password_credentials", "identity", t =>
                        {
                            t.HasCheckConstraint("ck_password_credentials_failure_count", "failed_attempt_count >= 0");

                            t.HasCheckConstraint("ck_password_credentials_hash_state", "(status = 'PendingSetup' and encoded_hash is null) or (status <> 'PendingSetup' and encoded_hash is not null)");

                            t.HasCheckConstraint("ck_password_credentials_status", "status in ('PendingSetup', 'Active', 'Disabled')");
                        });
                });

            modelBuilder.Entity("Kalm.Identity.Domain.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("ActivatedAtUtc")
                        .HasColumnType("timestamptz")
                        .HasColumnName("activated_at_utc");

                    b.Property<DateTimeOffset?>("ArchivedAtUtc")
                        .HasColumnType("timestamptz")
                        .HasColumnName("archived_at_utc");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("display_name");

                    b.Property<string>("Email")
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("email");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("normalized_email");

                    b.Property<string>("NormalizedUsername")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("normalized_username");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<string>("PreferredLanguage")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("preferred_language");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at_utc");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("username");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .IsUnique()
                        .HasDatabaseName("ux_users_normalized_email")
                        .HasFilter("normalized_email is not null");

                    b.HasIndex("NormalizedUsername")
                        .IsUnique()
                        .HasDatabaseName("ux_users_normalized_username");

                    b.ToTable("users", "identity", t =>
                        {
                            t.HasCheckConstraint("ck_users_preferred_language", "preferred_language in ('en', 'ar')");

                            t.HasCheckConstraint("ck_users_status", "status in ('Suspended', 'Active', 'Archived')");
                        });
                });

            modelBuilder.Entity("Kalm.Identity.Domain.UserSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("AbsoluteExpiresAtUtc")
                        .HasColumnType("timestamptz")
                        .HasColumnName("absolute_expires_at_utc");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at_utc");

                    b.Property<DateTimeOffset>("InactivityExpiresAtUtc")
                        .HasColumnType("timestamptz")
                        .HasColumnName("inactivity_expires_at_utc");

                    b.Property<DateTimeOffset>("LastActivityAtUtc")
                        .HasColumnType("timestamptz")
                        .HasColumnName("last_activity_at_utc");

                    b.Property<DateTimeOffset>("LastReauthenticatedAtUtc")
                        .HasColumnType("timestamptz")
                        .HasColumnName("last_reauthenticated_at_utc");

                    b.Property<string>("RevocationReason")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("revocation_reason");

                    b.Property<DateTimeOffset?>("RevokedAtUtc")
                        .HasColumnType("timestamptz")
                        .HasColumnName("revoked_at_utc");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("InactivityExpiresAtUtc")
                        .HasDatabaseName("ix_user_sessions_inactivity_expires_at_utc");

                    b.HasIndex("UserId", "RevokedAtUtc", "AbsoluteExpiresAtUtc")
                        .HasDatabaseName("ix_user_sessions_user_id_revoked_at_absolute_expires_at");

                    b.ToTable("user_sessions", "identity", t =>
                        {
                            t.HasCheckConstraint("ck_user_sessions_expiry", "created_at_utc <= last_activity_at_utc and last_activity_at_utc < inactivity_expires_at_utc and inactivity_expires_at_utc <= absolute_expires_at_utc");

                            t.HasCheckConstraint("ck_user_sessions_revocation_reason", "(revoked_at_utc is null and revocation_reason is null) or (revoked_at_utc is not null and revocation_reason is not null)");
                        });
                });

            modelBuilder.Entity("Kalm.Identity.Domain.LoginAttempt", b =>
                {
                    b.HasOne("Kalm.Identity.Domain.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Kalm.Identity.Domain.PasswordCredential", b =>
                {
                    b.HasOne("Kalm.Identity.Domain.User", null)
                        .WithOne()
                        .HasForeignKey("Kalm.Identity.Domain.PasswordCredential", "UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Kalm.Identity.Domain.UserSession", b =>
                {
                    b.HasOne("Kalm.Identity.Domain.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
