// <auto-generated />
using System;
using Kalm.Identity.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Kalm.Identity.Infrastructure.Migrations
{
    [DbContext(typeof(IdentityDbContext))]
    partial class IdentityDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("identity")
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Kalm.Identity.Domain.LoginAttempt", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("correlation_id");

                    b.Property<int>("FingerprintKeyVersion")
                        .HasColumnType("integer")
                        .HasColumnName("fingerprint_key_version");

                    b.Property<string>("IdentifierFingerprint")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("identifier_fingerprint");

                    b.Property<string>("NetworkIdentifier")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("network_identifier");

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .HasColumnType("timestamptz")
                        .HasColumnName("occurred_at_utc");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("outcome");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("IdentifierFingerprint", "OccurredAtUtc")
                        .HasDatabaseName("ix_login_attempts_identifier_fingerprint_occurred_at_utc");

                    b.HasIndex("NetworkIdentifier", "OccurredAtUtc")
                        .HasDatabaseName("ix_login_attempts_network_identifier_occurred_at_utc");

                    b.HasIndex("UserId", "OccurredAtUtc")
                        .HasDatabaseName("ix_login_attempts_user_id_occurred_at_utc");

                    b.ToTable("login_attempts", "identity", t =>
                        {
                            t.HasCheckConstraint("ck_login_attempts_outcome", "outcome in ('Succeeded', 'InvalidCredentials', 'Locked', 'Ineligible')");
                        });
                });

            modelBuilder.Entity("Kalm.Identity.Domain.PasswordCredential", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("EncodedHash")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("encoded_hash");

                    b.Property<int>("FailedAttemptCount")
                        .HasColumnType("integer")
                        .HasColumnName("failed_attempt_count");

                    b.Property<DateTimeOffset?>("FailureWindowStartedAtUtc")
                        .HasColumnType("timestamptz")
                        .HasColumnName("failure_window_started_at_utc");

                    b.Property<DateTimeOffset?>("LockedUntilUtc")
                        .HasColumnType("timestamptz")
                        .HasColumnName("locked_until_utc");

                    b.Property<DateTimeOffset?>("PasswordChangedAtUtc")
                        .HasColumnType("timestamptz")
                        .HasColumnName("password_changed_at_utc");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at_utc");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("ux_password_credentials_user_id");

                    b.ToTable("password_credentials", "identity", t =>
                        {
                            t.HasCheckConstraint("ck_password_credentials_failure_count", "failed_attempt_count >= 0");

                            t.HasCheckConstraint("ck_password_credentials_hash_state", "(status = 'PendingSetup' and encoded_hash is null) or (status <> 'PendingSetup' and encoded_hash is not null)");

                            t.HasCheckConstraint("ck_password_credentials_status", "status in ('PendingSetup', 'Active', 'Disabled')");
                        });
                });

            modelBuilder.Entity("Kalm.Identity.Domain.Permission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at_utc");

                    b.Property<DateTimeOffset?>("RetiredAtUtc")
                        .HasColumnType("timestamptz")
                        .HasColumnName("retired_at_utc");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ux_permissions_code");

                    b.ToTable("permissions", "identity", t =>
                        {
                            t.HasCheckConstraint("ck_permissions_code", "code ~ '^[a-z][a-z0-9_]*(\\.[a-z][a-z0-9_]*)+$'");

                            t.HasCheckConstraint("ck_permissions_retired_state", "(status = 'Active' and retired_at_utc is null) or (status = 'Retired' and retired_at_utc is not null)");

                            t.HasCheckConstraint("ck_permissions_status", "status in ('Active', 'Retired')");
                        });
                });

            modelBuilder.Entity("Kalm.Identity.Domain.PinCredential", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("EncodedHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("encoded_hash");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at_utc");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("ux_pin_credentials_user_id");

                    b.ToTable("pin_credentials", "identity");
                });

            modelBuilder.Entity("Kalm.Identity.Domain.PinLoginAttempt", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("correlation_id");

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("uuid")
                        .HasColumnName("device_id");

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .HasColumnType("timestamptz")
                        .HasColumnName("occurred_at_utc");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("outcome");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("DeviceId", "UserId", "OccurredAtUtc")
                        .HasDatabaseName("ix_pin_login_attempts_device_user_occurred");

                    b.ToTable("pin_login_attempts", "identity", t =>
                        {
                            t.HasCheckConstraint("ck_pin_login_attempts_outcome", "outcome in ('Succeeded', 'InvalidCredentials', 'Locked', 'Ineligible')");
                        });
                });

            modelBuilder.Entity("Kalm.Identity.Domain.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("ArchivedAtUtc")
                        .HasColumnType("timestamptz")
                        .HasColumnName("archived_at_utc");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("name");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("normalized_name");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<string>("SystemKey")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("system_key");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at_utc");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasAlternateKey("Id", "OrganizationId")
                        .HasName("ak_roles_id_organization_id");

                    b.HasIndex("OrganizationId", "NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("ux_roles_organization_id_normalized_name");

                    b.HasIndex("OrganizationId", "SystemKey")
                        .IsUnique()
                        .HasDatabaseName("ux_roles_organization_id_system_key")
                        .HasFilter("system_key is not null");

                    b.HasIndex("OrganizationId", "Status", "NormalizedName", "Id")
                        .HasDatabaseName("ix_roles_organization_status_normalized_name_id");

                    b.ToTable("roles", "identity", t =>
                        {
                            t.HasCheckConstraint("ck_roles_archived_state", "(status = 'Active' and archived_at_utc is null) or (status = 'Archived' and archived_at_utc is not null)");

                            t.HasCheckConstraint("ck_roles_status", "status in ('Active', 'Archived')");
                        });
                });

            modelBuilder.Entity("Kalm.Identity.Domain.RolePermission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("GrantedAtUtc")
                        .HasColumnType("timestamptz")
                        .HasColumnName("granted_at_utc");

                    b.Property<Guid>("PermissionId")
                        .HasColumnType("uuid")
                        .HasColumnName("permission_id");

                    b.Property<DateTimeOffset?>("RevokedAtUtc")
                        .HasColumnType("timestamptz")
                        .HasColumnName("revoked_at_utc");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("PermissionId");

                    b.HasIndex("RoleId", "PermissionId")
                        .IsUnique()
                        .HasDatabaseName("ux_role_permissions_active")
                        .HasFilter("revoked_at_utc is null");

                    b.ToTable("role_permissions", "identity", t =>
                        {
                            t.HasCheckConstraint("ck_role_permissions_revocation", "revoked_at_utc is null or revoked_at_utc >= granted_at_utc");
                        });
                });

            modelBuilder.Entity("Kalm.Identity.Domain.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("ActivatedAtUtc")
                        .HasColumnType("timestamptz")
                        .HasColumnName("activated_at_utc");

                    b.Property<DateTimeOffset?>("ArchivedAtUtc")
                        .HasColumnType("timestamptz")
                        .HasColumnName("archived_at_utc");

                    b.Property<long>("AuthorizationVersion")
                        .HasColumnType("bigint")
                        .HasColumnName("authorization_version");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("display_name");

                    b.Property<string>("Email")
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("email");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("normalized_email");

                    b.Property<string>("NormalizedUsername")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("normalized_username");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<string>("PreferredLanguage")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("preferred_language");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at_utc");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("username");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasAlternateKey("Id", "OrganizationId")
                        .HasName("ak_users_id_organization_id");

                    b.HasIndex("NormalizedEmail")
                        .IsUnique()
                        .HasDatabaseName("ux_users_normalized_email")
                        .HasFilter("normalized_email is not null");

                    b.HasIndex("NormalizedUsername")
                        .IsUnique()
                        .HasDatabaseName("ux_users_normalized_username");

                    b.ToTable("users", "identity", t =>
                        {
                            t.HasCheckConstraint("ck_users_preferred_language", "preferred_language in ('en', 'ar')");

                            t.HasCheckConstraint("ck_users_status", "status in ('Suspended', 'Active', 'Archived')");
                        });
                });

            modelBuilder.Entity("Kalm.Identity.Domain.UserRoleAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("AssignedAtUtc")
                        .HasColumnType("timestamptz")
                        .HasColumnName("assigned_at_utc");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<DateTimeOffset?>("RevokedAtUtc")
                        .HasColumnType("timestamptz")
                        .HasColumnName("revoked_at_utc");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("RoleId", "OrganizationId");

                    b.HasIndex("RoleId", "UserId")
                        .HasDatabaseName("ix_user_role_assignments_role_id_user_id_active")
                        .HasFilter("revoked_at_utc is null");

                    b.HasIndex("UserId", "OrganizationId");

                    b.HasIndex("UserId", "RevokedAtUtc")
                        .HasDatabaseName("ix_user_role_assignments_user_id_revoked_at_utc");

                    b.HasIndex("UserId", "RoleId")
                        .IsUnique()
                        .HasDatabaseName("ux_user_role_assignments_active")
                        .HasFilter("revoked_at_utc is null");

                    b.ToTable("user_role_assignments", "identity", t =>
                        {
                            t.HasCheckConstraint("ck_user_role_assignments_revocation", "revoked_at_utc is null or revoked_at_utc >= assigned_at_utc");
                        });
                });

            modelBuilder.Entity("Kalm.Identity.Domain.UserSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("AbsoluteExpiresAtUtc")
                        .HasColumnType("timestamptz")
                        .HasColumnName("absolute_expires_at_utc");

                    b.Property<long>("AuthorizationVersion")
                        .HasColumnType("bigint")
                        .HasColumnName("authorization_version");

                    b.Property<Guid?>("BranchId")
                        .HasColumnType("uuid")
                        .HasColumnName("branch_id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid?>("DeviceId")
                        .HasColumnType("uuid")
                        .HasColumnName("device_id");

                    b.Property<int?>("DeviceSecurityVersion")
                        .HasColumnType("integer")
                        .HasColumnName("device_security_version");

                    b.Property<DateTimeOffset>("InactivityExpiresAtUtc")
                        .HasColumnType("timestamptz")
                        .HasColumnName("inactivity_expires_at_utc");

                    b.Property<DateTimeOffset>("LastActivityAtUtc")
                        .HasColumnType("timestamptz")
                        .HasColumnName("last_activity_at_utc");

                    b.Property<DateTimeOffset>("LastReauthenticatedAtUtc")
                        .HasColumnType("timestamptz")
                        .HasColumnName("last_reauthenticated_at_utc");

                    b.Property<long?>("PinCredentialVersion")
                        .HasColumnType("bigint")
                        .HasColumnName("pin_credential_version");

                    b.Property<string>("RevocationReason")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("revocation_reason");

                    b.Property<DateTimeOffset?>("RevokedAtUtc")
                        .HasColumnType("timestamptz")
                        .HasColumnName("revoked_at_utc");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("InactivityExpiresAtUtc")
                        .HasDatabaseName("ix_user_sessions_inactivity_expires_at_utc");

                    b.HasIndex("DeviceId", "RevokedAtUtc")
                        .HasDatabaseName("ix_user_sessions_device_id_revoked_at_utc");

                    b.HasIndex("UserId", "RevokedAtUtc", "AbsoluteExpiresAtUtc")
                        .HasDatabaseName("ix_user_sessions_user_id_revoked_at_absolute_expires_at");

                    b.ToTable("user_sessions", "identity", t =>
                        {
                            t.HasCheckConstraint("ck_user_sessions_expiry", "created_at_utc <= last_activity_at_utc and last_activity_at_utc < inactivity_expires_at_utc and inactivity_expires_at_utc <= absolute_expires_at_utc");

                            t.HasCheckConstraint("ck_user_sessions_revocation_reason", "(revoked_at_utc is null and revocation_reason is null) or (revoked_at_utc is not null and revocation_reason is not null)");
                        });
                });

            modelBuilder.Entity("Kalm.Identity.Domain.LoginAttempt", b =>
                {
                    b.HasOne("Kalm.Identity.Domain.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Kalm.Identity.Domain.PasswordCredential", b =>
                {
                    b.HasOne("Kalm.Identity.Domain.User", null)
                        .WithOne()
                        .HasForeignKey("Kalm.Identity.Domain.PasswordCredential", "UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Kalm.Identity.Domain.PinCredential", b =>
                {
                    b.HasOne("Kalm.Identity.Domain.User", null)
                        .WithOne()
                        .HasForeignKey("Kalm.Identity.Domain.PinCredential", "UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Kalm.Identity.Domain.PinLoginAttempt", b =>
                {
                    b.HasOne("Kalm.Identity.Domain.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Kalm.Identity.Domain.RolePermission", b =>
                {
                    b.HasOne("Kalm.Identity.Domain.Permission", null)
                        .WithMany()
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Kalm.Identity.Domain.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Kalm.Identity.Domain.UserRoleAssignment", b =>
                {
                    b.HasOne("Kalm.Identity.Domain.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId", "OrganizationId")
                        .HasPrincipalKey("Id", "OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Kalm.Identity.Domain.User", null)
                        .WithMany()
                        .HasForeignKey("UserId", "OrganizationId")
                        .HasPrincipalKey("Id", "OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Kalm.Identity.Domain.UserSession", b =>
                {
                    b.HasOne("Kalm.Identity.Domain.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
