// <auto-generated />
using System;
using Kalm.Catalog.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Kalm.Catalog.Infrastructure.Migrations
{
    [DbContext(typeof(CatalogDbContext))]
    partial class CatalogDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("catalog")
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Kalm.Catalog.Domain.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ArabicName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("arabic_name");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at_utc");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer")
                        .HasColumnName("display_order");

                    b.Property<string>("EnglishName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("english_name");

                    b.Property<string>("IconCode")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("icon_code");

                    b.Property<string>("NormalizedArabicName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("normalized_arabic_name");

                    b.Property<string>("NormalizedEnglishName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("normalized_english_name");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<string>("PosColorToken")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("pos_color_token");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at_utc");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasAlternateKey("Id", "OrganizationId")
                        .HasName("ak_catalog_categories_id_organization_id");

                    b.HasIndex("OrganizationId", "NormalizedArabicName")
                        .IsUnique()
                        .HasDatabaseName("ux_catalog_categories_organization_arabic_name");

                    b.HasIndex("OrganizationId", "NormalizedEnglishName")
                        .IsUnique()
                        .HasDatabaseName("ux_catalog_categories_organization_english_name");

                    b.HasIndex("OrganizationId", "Status", "DisplayOrder", "Id")
                        .HasDatabaseName("ix_catalog_categories_organization_status_order_id");

                    b.ToTable("categories", "catalog", t =>
                        {
                            t.HasCheckConstraint("ck_catalog_categories_display_order", "display_order >= 0");

                            t.HasCheckConstraint("ck_catalog_categories_normalized_names", "length(normalized_arabic_name) > 0 and length(normalized_english_name) > 0");

                            t.HasCheckConstraint("ck_catalog_categories_status", "status in ('Active', 'Archived')");
                        });
                });

            modelBuilder.Entity("Kalm.Catalog.Domain.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ArabicDescription")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("arabic_description");

                    b.Property<string>("ArabicName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("arabic_name");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("category_id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at_utc");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer")
                        .HasColumnName("display_order");

                    b.Property<string>("EnglishDescription")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("english_description");

                    b.Property<string>("EnglishName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("english_name");

                    b.Property<string>("NormalizedArabicName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("normalized_arabic_name");

                    b.Property<string>("NormalizedEnglishName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("normalized_english_name");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("sku");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("product_type");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at_utc");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasAlternateKey("Id", "OrganizationId")
                        .HasName("ak_catalog_products_id_organization_id");

                    b.HasIndex("CategoryId", "OrganizationId");

                    b.HasIndex("OrganizationId", "Sku")
                        .IsUnique()
                        .HasDatabaseName("ux_catalog_products_organization_sku");

                    b.HasIndex("OrganizationId", "Status", "DisplayOrder", "Id")
                        .HasDatabaseName("ix_catalog_products_organization_status_order_id");

                    b.HasIndex("OrganizationId", "CategoryId", "Status", "DisplayOrder", "Id")
                        .HasDatabaseName("ix_catalog_products_organization_category_status_order_id");

                    b.ToTable("products", "catalog", t =>
                        {
                            t.HasCheckConstraint("ck_catalog_products_display_order", "display_order >= 0");

                            t.HasCheckConstraint("ck_catalog_products_normalized_values", "length(normalized_arabic_name) > 0 and length(normalized_english_name) > 0 and length(sku) > 0");

                            t.HasCheckConstraint("ck_catalog_products_status", "status in ('Active', 'Archived')");

                            t.HasCheckConstraint("ck_catalog_products_type", "product_type in ('MadeToOrder', 'PurchasedFinishedGood', 'ServiceNonStock')");
                        });
                });

            modelBuilder.Entity("Kalm.Catalog.Domain.ProductVariant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ArabicName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("arabic_name");

                    b.Property<string>("Barcode")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("barcode");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at_utc");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer")
                        .HasColumnName("display_order");

                    b.Property<string>("EnglishName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("english_name");

                    b.Property<string>("NormalizedArabicName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("normalized_arabic_name");

                    b.Property<string>("NormalizedEnglishName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("normalized_english_name");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.Property<string>("ServingFormatCode")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("serving_format_code");

                    b.Property<string>("SizeCode")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("size_code");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<string>("TemperatureCode")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("temperature_code");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId", "Barcode")
                        .IsUnique()
                        .HasDatabaseName("ux_catalog_product_variants_organization_barcode")
                        .HasFilter("barcode is not null");

                    b.HasIndex("OrganizationId", "Code")
                        .IsUnique()
                        .HasDatabaseName("ux_catalog_product_variants_organization_code");

                    b.HasIndex("ProductId", "OrganizationId");

                    b.HasIndex("ProductId", "Status", "DisplayOrder", "Id")
                        .HasDatabaseName("ix_catalog_product_variants_product_status_order_id");

                    b.ToTable("product_variants", "catalog", t =>
                        {
                            t.HasCheckConstraint("ck_catalog_product_variants_display_order", "display_order >= 0");

                            t.HasCheckConstraint("ck_catalog_product_variants_normalized_values", "length(normalized_arabic_name) > 0 and length(normalized_english_name) > 0 and length(code) > 0");

                            t.HasCheckConstraint("ck_catalog_product_variants_status", "status in ('Active', 'Archived')");
                        });
                });

            modelBuilder.Entity("Kalm.Catalog.Domain.Product", b =>
                {
                    b.HasOne("Kalm.Catalog.Domain.Category", null)
                        .WithMany()
                        .HasForeignKey("CategoryId", "OrganizationId")
                        .HasPrincipalKey("Id", "OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Kalm.Catalog.Domain.ProductVariant", b =>
                {
                    b.HasOne("Kalm.Catalog.Domain.Product", null)
                        .WithMany("Variants")
                        .HasForeignKey("ProductId", "OrganizationId")
                        .HasPrincipalKey("Id", "OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Kalm.Catalog.Domain.Product", b =>
                {
                    b.Navigation("Variants");
                });
#pragma warning restore 612, 618
        }
    }
}
