export const CATALOG_COPY = {
  en: {
    catalog: "Catalog", categories: "Categories", products: "Products",
    categoryIntro: "Organize the bilingual catalogue shared by every branch.",
    productIntro: "Manage products and variants without prices or branch availability.",
    createCategory: "New category", createProduct: "New product", search: "Search", status: "Status",
    all: "All", active: "Active", archived: "Archived", name: "Name", arabicName: "Arabic name",
    englishName: "English name", order: "Order", actions: "Actions", open: "Open", previous: "Previous",
    next: "Next", page: "Page", loading: "Loading…", retry: "Try again", empty: "No matching records.",
    error: "The catalogue could not be loaded.", moveUp: "Move up", moveDown: "Move down", backCategories: "Back to categories",
    backProducts: "Back to products", editCategory: "Edit category", editProduct: "Edit product", displayOrder: "Display order",
    color: "POS color", icon: "Icon", none: "None", save: "Save", invalid: "Review the highlighted required fields.",
    archive: "Archive", activate: "Activate", confirmArchive: "Archive this record?", confirmActivate: "Activate this record?",
    confirm: "Confirm", cancel: "Cancel", conflict: "A newer version is available.",
    refreshVersion: "Load latest version and keep my draft", archiveBlocked: "This category still has active products.",
    activeProducts: "Active products", sku: "SKU", category: "Category", productType: "Product type",
    variants: "Variants", variant: "Variant", addVariant: "Add variant", archiveVariant: "Archive variant",
    activateVariant: "Activate variant", code: "Code", barcode: "Barcode", size: "Size", temperature: "Temperature",
    serving: "Serving format", arabicDescription: "Arabic description", englishDescription: "English description",
    madeToOrder: "Made to order", purchasedFinishedGood: "Purchased finished good", serviceNonStock: "Service / non-stock",
    lifecycleConflict: "The category or active-variant requirement prevents this change.",
    navigation: "Catalog sections"
  },
  ar: {
    catalog: "الكتالوج", categories: "التصنيفات", products: "المنتجات",
    categoryIntro: "نظّم الكتالوج ثنائي اللغة المشترك بين جميع الفروع.",
    productIntro: "أدر المنتجات والمتغيرات دون الأسعار أو التوفر حسب الفرع.",
    createCategory: "تصنيف جديد", createProduct: "منتج جديد", search: "بحث", status: "الحالة",
    all: "الكل", active: "نشط", archived: "مؤرشف", name: "الاسم", arabicName: "الاسم العربي",
    englishName: "الاسم الإنجليزي", order: "الترتيب", actions: "الإجراءات", open: "فتح", previous: "السابق",
    next: "التالي", page: "الصفحة", loading: "جارٍ التحميل…", retry: "حاول مجددًا", empty: "لا توجد سجلات مطابقة.",
    error: "تعذّر تحميل الكتالوج.", moveUp: "تحريك لأعلى", moveDown: "تحريك لأسفل", backCategories: "العودة إلى التصنيفات",
    backProducts: "العودة إلى المنتجات", editCategory: "تعديل التصنيف", editProduct: "تعديل المنتج", displayOrder: "ترتيب العرض",
    color: "لون نقطة البيع", icon: "الأيقونة", none: "بدون", save: "حفظ", invalid: "راجع الحقول المطلوبة.",
    archive: "أرشفة", activate: "تفعيل", confirmArchive: "هل تريد أرشفة هذا السجل؟", confirmActivate: "هل تريد تفعيل هذا السجل؟",
    confirm: "تأكيد", cancel: "إلغاء", conflict: "توجد نسخة أحدث.",
    refreshVersion: "تحميل أحدث نسخة مع الاحتفاظ بمسودتي", archiveBlocked: "لا يزال لهذا التصنيف منتجات نشطة.",
    activeProducts: "المنتجات النشطة", sku: "رمز المخزون", category: "التصنيف", productType: "نوع المنتج",
    variants: "المتغيرات", variant: "متغير", addVariant: "إضافة متغير", archiveVariant: "أرشفة المتغير",
    activateVariant: "تفعيل المتغير", code: "الرمز", barcode: "الباركود", size: "الحجم", temperature: "درجة الحرارة",
    serving: "طريقة التقديم", arabicDescription: "الوصف العربي", englishDescription: "الوصف الإنجليزي",
    madeToOrder: "يُحضّر عند الطلب", purchasedFinishedGood: "منتج نهائي مشترى", serviceNonStock: "خدمة / غير مخزني",
    lifecycleConflict: "متطلبات التصنيف أو المتغير النشط تمنع هذا التغيير.",
    navigation: "أقسام الكتالوج"
  }
} as const;
